version: "3"
services:

  proxy:
    build: "."
    ports: 
      - "80:80"
      - "443:443"
    depends_on: 
      - "flask"
      - "react"
      - "neo4j"

  flask:
    build: "./backend"
    container_name: flask
    ports: 
      - "5000:5000"

  react:
    build: "./frontend"
    container_name: react
    ports: 
      - "80:80"

  neo4j:
    container_name: neo4j
    image: neo4j:4.4.3-enterprise
    volumes:
      - "./data:/var/lib/neo4j/import"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4J_AUTH: "neo4j/bio4tdummy"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_import_file_enabled: 'true'

    
    