version: "3"
services:

  proxy:
    build: "."
    ports: 
      - "443:443"
    depends_on: 
      - "flask"
      - "react"

  flask:
    build: "./backend"
    container_name: flask
    ports: 
      - "5000:5000"
    volumes:
      - ./backend:/usr/local/app/backend
    command: bash -c 
      "pwd && ls -l && chmod 777 ./wait.sh && ./wait.sh neo4j 7687 neo4j && cd databaseUtils && python Import.py && python apiFlask.py neo4j 7687"
    depends_on:
      - neo4j
    environment:
      NEOSERVER: 'neo4j'
      NEOPORT: "7687"


  react:
    build: "./frontend"
    container_name: react
    ports: 
      - "8080:80"
    links:
      - neo4j:db
    depends_on:
      - "neo4j"

  neo4j:
    container_name: neo4j
    image: neo4j:4.4.3-enterprise
    volumes:
      - "./backend/data:/var/lib/neo4j/import"
      - "./backend/plugins:/var/lib/neo4j/plugins"

    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4J_AUTH: "neo4j/bio4tdummy"
      NEO4JLABS_PLUGINS: '[]'
      NEO4J_apoc_import_file_enabled: 'true'

    
    